[book]
title = "Cracking the Systems Engineering Interview"
description = "Linux, Docker, and Kubernetes for the Cloud Platform Interview"
authors = ["Arpan Pathak"]
language = "en"
src = "src"

[build]
build-dir = "book"
create-missing = false

[output.html]
default-theme = "light"
additional-css = ["theme/custom.css"]
smart-punctuation = true
