[book]
title = "Coding Interviews for Cracked Rustaceans"
description = "A Zero-Cost Abstraction Obsession Anatomy"
authors = ["Arpan Pathak"]
language = "en"
src = "src"

[build]
build-dir = "book"
create-missing = false

[output.html]
default-theme = "light"
additional-css = ["theme/custom.css"]
smart-punctuation = true
