[book]
title = "GPU-Accelerated Kubernetes - Distributed GPU Kernel & Job Scheduling in a Cloud Native Way"
authors = ["Arpan Pathak"]
language = "en"
src = "src"

[build]
build-dir = "book"
create-missing = false

[output.html]
default-theme = "light"
additional-css = ["theme/custom.css"]
smart-punctuation = true
