[book]
title = "GPU-Accelerated Kubernetes - Distributed GPU Kernel & Job Scheduling in a Cloud Native Way"
authors = ["Arpan Pathak"]
language = "en"
src = "src"

[build]
build-dir = "book"
create-missing = false

[output.html]
default-theme = "light"
additional-css = ["theme/custom.css"]
smart-punctuation = true
git-repository-url = "https://github.com/arpanpathak/cracking-the-systems-programming-interview/tree/prep-v2/gpu-accelerated-kubernetes"
git-repository-icon = "fab-github"
edit-url-template = "https://github.com/arpanpathak/cracking-the-systems-programming-interview/edit/prep-v2/gpu-accelerated-kubernetes/{path}"
