apiVersion: v1
kind: Pod
metadata:
  name: gpu-env
spec:
  restartPolicy: Never
  containers:
    - name: check
      image: gpu-check:1
      imagePullPolicy: Never
      command: ["sleep", "300"]
      resources:
        limits:
          nvidia.com/gpu: 1
