apiVersion: v1
kind: Pod
metadata:
  name: gpu-info
spec:
  restartPolicy: Never
  containers:
    - name: info
      image: gpu-sharing:1
      imagePullPolicy: Never
      command: ["gpu_info"]
      resources:
        limits:
          nvidia.com/gpu: 1
