[book]
title = "Cracking the Systems Programming Interview"
description = "Rust from data structures to the kernel boundary"
authors = ["Arpan Pathak"]
language = "en"
src = "src"

[build]
build-dir = "book"
create-missing = false

[rust]
edition = "2024"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
additional-css = ["theme/custom.css"]
additional-js = ["theme/anim.js"]
smart-punctuation = true
git-repository-url = "https://github.com/arpanpathak/cracking-the-systems-programming-interview/tree/prep-v2/cracking-the-systems-programming-interview"
git-repository-icon = "fab-github"

[output.html.playground]
runnable = false
copyable = true

[output.html.fold]
enable = true
level = 1
